apiVersion: gpio.scmeyer.dev/v1alpha1
kind: PinClaim
metadata:
  labels:
    app.kubernetes.io/name: src
    app.kubernetes.io/managed-by: kustomize
  name: pinclaim-sample
spec:
  # TODO(user): Add fields here
